name: 'Notify TMS App'
description: 'Send workflow results to YouTrack TMS App webhook'
inputs:
  triggerSource:
    description: 'Source of trigger (YT issue ID, test repo, etc.)'
    required: false
  testCaseId:
    description: 'Original Test Case ID'
    required: true
  testRunId:
    description: 'Test Run ID (parent suite)'
    required: true
  individualTestRunId:
    description: 'Individual Test Run ID (specific test case run)'
    required: false
  totalTests:
    description: 'Total number of tests in suite'
    required: false
  passedTests:
    description: 'Number of passed tests'
    required: false
  failedTests:
    description: 'Number of failed tests'
    required: false
  failedTestsList:
    description: 'Comma-separated list of failed test names'
    required: false
  callbackUrl:
    description: 'Full webhook URL to TMS App endpoint'
    required: true
  youtrackToken:
    description: 'YouTrack API token for authentication (optional)'
    required: false
  errorDetails:
    description: 'Error details for individual test runs'
    required: false
  logs:
    description: 'Test execution logs'
    required: false
  assertionDetails:
    description: 'Assertion failure details'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Determine workflow status
      id: status
      shell: bash
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "status=success" >> $GITHUB_OUTPUT
        elif [ "${{ job.status }}" == "failure" ]; then
          echo "status=failure" >> $GITHUB_OUTPUT
        elif [ "${{ job.status }}" == "cancelled" ]; then
          echo "status=cancelled" >> $GITHUB_OUTPUT
        else
          echo "status=unknown" >> $GITHUB_OUTPUT
        fi

    - name: Calculate success rate
      id: success_rate
      shell: bash
      run: |
        if [ -n "${{ inputs.totalTests }}" ] && [ "${{ inputs.totalTests }}" != "0" ]; then
          if [ -n "${{ inputs.passedTests }}" ]; then
            RATE=$(echo "scale=2; ${{ inputs.passedTests }} * 100 / ${{ inputs.totalTests }}" | bc)
            echo "rate=$RATE" >> $GITHUB_OUTPUT
          else
            echo "rate=0" >> $GITHUB_OUTPUT
          fi
        else
          echo "rate=" >> $GITHUB_OUTPUT
        fi

    - name: Prepare and send webhook payload
      shell: bash
      run: |
        set +e
        
        # Parse failed tests list
        FAILED_LIST="[]"
        if [ -n "${{ inputs.failedTestsList }}" ]; then
          # Convert comma-separated string to JSON array
          FAILED_LIST=$(echo "${{ inputs.failedTestsList }}" | jq -R -s -c 'split(",") | map(gsub("^\\s+|\\s+$"; ""))')
        fi

        # Build suite results if provided
        SUITE_RESULTS="null"
        if [ -n "${{ inputs.totalTests }}" ]; then
          SUITE_RESULTS=$(jq -n \
            --arg total "${{ inputs.totalTests }}" \
            --arg passed "${{ inputs.passedTests }}" \
            --arg failed "${{ inputs.failedTests }}" \
            --arg rate "${{ steps.success_rate.outputs.rate }}" \
            --argjson failedList "$FAILED_LIST" \
            '{
              totalTests: ($total | tonumber),
              passedTests: ($passed | tonumber),
              failedTests: ($failed | tonumber),
              successRate: (if $rate != "" then ($rate | tonumber) else null end),
              failedTestsList: $failedList
            }')
        fi

        # Build individual results if provided
        INDIVIDUAL_RESULTS="null"
        if [ -n "${{ inputs.errorDetails }}" ] || [ -n "${{ inputs.logs }}" ] || [ -n "${{ inputs.assertionDetails }}" ]; then
          INDIVIDUAL_RESULTS=$(jq -n \
            --arg error "${{ inputs.errorDetails }}" \
            --arg logs "${{ inputs.logs }}" \
            --arg assertion "${{ inputs.assertionDetails }}" \
            '{
              errorDetails: (if $error != "" then $error else null end),
              logs: (if $logs != "" then $logs else null end),
              assertionDetails: (if $assertion != "" then $assertion else null end)
            }')
        fi

        # Build workflow context
        WORKFLOW_CONTEXT=$(jq -n \
          --arg name "${{ github.workflow }}" \
          --arg runNumber "${{ github.run_number }}" \
          --arg actor "${{ github.actor }}" \
          '{
            name: $name,
            runNumber: ($runNumber | tonumber),
            actor: $actor
          }')

        # Build job context
        JOB_CONTEXT=$(jq -n \
          --arg status "${{ steps.status.outputs.status }}" \
          '{
            status: $status
          }')

        # Build runner context
        RUNNER_CONTEXT=$(jq -n \
          --arg os "${{ runner.os }}" \
          --arg arch "${{ runner.arch }}" \
          '{
            os: $os,
            arch: $arch
          }')

        # Build complete payload and save to file
        PAYLOAD_FILE=$(mktemp)
        jq -n \
          --arg repo "${{ github.repository }}" \
          --arg runId "${{ github.run_id }}" \
          --arg status "${{ steps.status.outputs.status }}" \
          --arg event "${{ github.event_name }}" \
          --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
          --arg testCaseId "${{ inputs.testCaseId }}" \
          --arg testRunId "${{ inputs.testRunId }}" \
          --arg individualTestRunId "${{ inputs.individualTestRunId }}" \
          --arg triggerSource "${{ inputs.triggerSource }}" \
          --argjson suiteResults "$SUITE_RESULTS" \
          --argjson individualResults "$INDIVIDUAL_RESULTS" \
          --argjson workflow "$WORKFLOW_CONTEXT" \
          --argjson job "$JOB_CONTEXT" \
          --argjson runner "$RUNNER_CONTEXT" \
          '{
            repository: $repo,
            run_id: $runId,
            status: $status,
            event: $event,
            timestamp: $timestamp,
            testCaseId: $testCaseId,
            testRunId: $testRunId,
            individualTestRunId: (if $individualTestRunId != "" then $individualTestRunId else null end),
            triggerSource: (if $triggerSource != "" then $triggerSource else null end),
            suiteResults: (if $suiteResults != "null" then $suiteResults else null end),
            individualResults: (if $individualResults != "null" then $individualResults else null end),
            workflow: $workflow,
            job: $job,
            runner: $runner
          }' > "$PAYLOAD_FILE"

        echo "Payload prepared:"
        cat "$PAYLOAD_FILE" | jq '.'

        # Send POST request to YouTrack webhook
        if [ -n "${{ inputs.youtrackToken }}" ]; then
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ inputs.youtrackToken }}" \
            -d "@$PAYLOAD_FILE" \
            "${{ inputs.callbackUrl }}")
        else
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -d "@$PAYLOAD_FILE" \
            "${{ inputs.callbackUrl }}")
        fi

        # Clean up temp file
        rm -f "$PAYLOAD_FILE"

        # Parse response
        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        BODY=$(echo "$RESPONSE" | sed '$d')

        if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
          echo "✅ Successfully notified TMS App"
          if [ -n "$BODY" ]; then
            echo "Response: $BODY"
          fi
        else
          echo "❌ Failed to notify TMS App (HTTP $HTTP_CODE)"
          if [ -n "$BODY" ]; then
            echo "Response: $BODY"
          fi
          exit 1
        fi

