name: CI-2

on:
  workflow_dispatch:
    inputs:
      triggerSource:
        description: "Source of trigger (YT issue ID, test repo, etc.)"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run example
        run: echo "Hello from workflow"

      - name: Notify YouTrack app
        if: ${{ always() }}
        uses: actions/github-script@v7
        with:
          script: |
            const body = {
              repository: process.env.GITHUB_REPOSITORY,
              run_id: process.env.GITHUB_RUN_ID,
              status: '${{ job.status }}',
              event: process.env.GITHUB_EVENT_NAME,
              triggerSource: '${{ github.event.inputs.triggerSource }}',
              timestamp: new Date().toISOString()
            };

            const res = await fetch(process.env.CALLBACK_URL, {
              method: 'POST',
              headers: { 
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${process.env.YOUTRACK_TOKEN}`
              },
              body: JSON.stringify(body)
            });

            if (!res.ok) {
              const text = await res.text();
              core.setFailed(`Webhook failed: ${res.status} ${res.statusText} - ${text}`);
            }
        env:
          CALLBACK_URL: ${{ secrets.WEBHOOK_URL }}
          YOUTRACK_TOKEN: ${{ secrets.YOUTRACK_TOKEN }}
