name: Unhappy Pass Test for TMS

on:
  workflow_dispatch:
    inputs:
      triggerSource:
        description: "Source of trigger (YT issue ID, test repo, etc.)"
        required: false
      testCaseId:
        description: "Original Test Case ID"
        required: true
      testRunId:
        description: "Test Run ID of a Test Case"
        required: true

jobs:
  auto-fail-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show test context
        run: |
          echo "🧪 Auto-Fail Test Starting..."
          echo "Test Case ID: ${{ github.event.inputs.testCaseId }}"
          echo "Test Run ID: ${{ github.event.inputs.testRunId }}"
          echo "Trigger Source: ${{ github.event.inputs.triggerSource }}"
          echo "Repository: ${{ github.repository }}"
          echo "Run ID: ${{ github.run_id }}"

      - name: Run failing tests
        run: |
          echo "🚀 Starting test execution..."
          echo "Setting up test environment..."
          sleep 1
          
          echo "Running test suite..."
          echo "✅ Test 1: User authentication - PASSED"
          echo "✅ Test 2: Data validation - PASSED"
          echo "✅ Test 3: API endpoints - PASSED"
          sleep 1
          
          echo "❌ Test 4: Critical business logic - FAILED"
          echo "   Expected: user.isActive = true"
          echo "   Actual: user.isActive = false"
          echo "   AssertionError: User should be active after registration"
          
          echo "❌ Test 5: Integration test - FAILED"
          echo "   Error: Connection timeout to external service"
          echo "   Details: Unable to connect to payment gateway after 30 seconds"
          
          echo ""
          echo "📊 Test Results Summary:"
          echo "   Total: 5 tests"
          echo "   Passed: 3"
          echo "   Failed: 2"
          echo "   Success Rate: 60%"
          echo ""
          echo "💥 Test suite failed - 2 critical failures detected"
          
          # Always exit with failure
          exit 1

      - name: Notify TMS App
        if: always()
        uses: ./.github/actions/notify-tms
        with:
          triggerSource: ${{ github.event.inputs.triggerSource }}
          testCaseId: ${{ github.event.inputs.testCaseId }}
          testRunId: ${{ github.event.inputs.testRunId }}
          totalTests: 5
          passedTests: 3
          failedTests: 2
          failedTestsList: "Critical business logic test, Integration test - payment gateway"
          callbackUrl: ${{ secrets.WEBHOOK_URL }}
          youtrackToken: ${{ secrets.YOUTRACK_TOKEN }}
        env:
          CALLBACK_URL: ${{ secrets.WEBHOOK_URL }}
          YOUTRACK_TOKEN: ${{ secrets.YOUTRACK_TOKEN }}
